name: glotelho_livreur
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.0.0
  firebase_database: ^11.0.0

  # État de l'application
  provider: ^6.1.2

  # Réseau / API
  dio: ^5.7.0

  # Persistance locale (session, token)
  shared_preferences: ^2.3.3

  # Sélection d'images (photos CNI, permis, véhicule, profil)
  image_picker: ^1.1.2

  # Carte (suivi livraison, statuts colorés par point)
  google_maps_flutter: ^2.9.0

  # Géolocalisation (position en temps réel du livreur)
  geolocator: ^13.0.2

  # Gestion des permissions (caméra, localisation)
  permission_handler: ^11.3.1

  # Signature du client à la livraison (point 6)
  signature: ^5.5.0

  # Formatage dates/heures (disponibilités, historique)
  intl: ^0.19.0
  google_sign_in: ^6.2.2
  url_launcher: ^6.3.0
  http: ^1.2.2

  # Authentification biométrique (empreinte / visage)
  local_auth: ^2.3.0

  # Coffre sécurisé (stockage du token pour la connexion biométrique)
  flutter_secure_storage: ^9.2.2
   # Notifications locales (simulation push en attendant Firebase)
  flutter_local_notifications: ^18.0.1


  # Firebase — suivi GPS temps réel
  


dev_dependencies:
  device_preview: ^1.2.0
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#0D1B2A"
  image: assets/images/glotelho_delivery_logo_high_contrast.png
  android_12:
    color: "#0D1B2A"
    image: assets/images/glotelho_delivery_logo_high_contrast.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/glotelho_delivery_logo_high_contrast.png"
  #image_scale: 3
  adaptive_icon_background: "#0D1B2A"
  adaptive_icon_foreground: "assets/images/glotelho_delivery_logo_high_contrast.png"